[application]
name = "LogOut"
default_platform = "web"

[bundle]
identifier = "com.gfaure.logworkout"
publisher = "gfaure"

[web.app]
title = "LogOut - Workout Logger"

[web.watcher]
reload_html = true
index_on_404 = true

